# Copyright 2026 unpatterned.org
# SPDX-License-Identifier: Apache-2.0

"""The vNext runtime entry point and durable domain contracts."""

from __future__ import annotations

from ._adapters import (
    adapt_coreference_receipt,
    adapt_reconcile_result,
    reviewed_reconcile_evidence,
)
from ._agent_planning import AgentPlanAdvice
from ._benchmarks import (
    BENCHMARK_RESULT_BUNDLE_SCHEMA,
    BenchmarkResultBundle,
    benchmark_result_bundle_from_record,
    qualification_from_evaluated_result,
    read_benchmark_result_bundle,
    write_benchmark_result_bundle,
)
from ._cases import what_would_resolve
from ._connectors import (
    EvidenceConnector,
    ExternalEvidenceRequest,
    HttpEvidenceConnector,
    HttpEvidenceResponse,
)
from ._document_execution import (
    DoclingDocumentIngestionExecutor,
    DocumentIngestionExecutor,
    DocumentIngestionRequest,
)
from ._document_observations import (
    DocumentIngestion,
    document_ingestion_from_parsed_document,
    observation_from_document,
    observation_from_document_ingestion,
)
from ._document_proposals import (
    DocumentProposalSet,
    reviewed_document_evidence,
    reviewed_document_proposals,
)
from ._execution import PolicyDecisionExecutor, PolicyExecution
from ._method_execution import (
    DomainResolutionMethodExecutor,
    PinnedResolutionMethodExecutor,
    ResolutionMethodExecution,
    ResolutionMethodExecutor,
    SplinkResolutionMethodExecutor,
)
from ._models import (
    ActionObservation,
    CaseEvent,
    Claim,
    ClaimProposal,
    Contradiction,
    DecisionReceipt,
    DocumentClaimSpec,
    DocumentRelationSpec,
    Entity,
    EntityMemory,
    EntityRelation,
    Evidence,
    EvidenceAction,
    EvidenceGap,
    Observation,
    OpenQuestion,
    PolicyDecision,
    ProposalAcceptance,
    ProposalAcceptancePolicy,
    RelationProposal,
    ResolutionCase,
    ResolutionDecisionPolicy,
    ResolutionIntent,
    ResolutionMethod,
    ResolutionMethodApproval,
    ResolutionRun,
    ToolCapability,
    new_entity_id,
    new_evidence_action_id,
    new_ledger_id,
    new_resolution_case_id,
)
from ._planning import (
    CaseAssessment,
    DeterministicResolutionPlanner,
    EvidencePlan,
    MethodAssessment,
    MethodBenchmarkQualification,
    PlannedEvidenceAction,
    PlannedResolutionMethod,
    ResolutionBudget,
)
from ._reviewed_artifacts import (
    ReviewedResolutionArtifact,
    ReviewedResolutionEdge,
    adapt_reviewed_resolution_artifact,
    reviewed_resolution_evidence,
)
from .engine import ArcheEngine, attach

__all__ = [
    "ArcheEngine",
    "ActionObservation",
    "AgentPlanAdvice",
    "BENCHMARK_RESULT_BUNDLE_SCHEMA",
    "BenchmarkResultBundle",
    "CaseEvent",
    "CaseAssessment",
    "Claim",
    "ClaimProposal",
    "Contradiction",
    "DecisionReceipt",
    "DeterministicResolutionPlanner",
    "DocumentIngestion",
    "DocumentIngestionExecutor",
    "DocumentIngestionRequest",
    "DocumentClaimSpec",
    "DocumentProposalSet",
    "DocumentRelationSpec",
    "DoclingDocumentIngestionExecutor",
    "DomainResolutionMethodExecutor",
    "EvidenceAction",
    "Entity",
    "EntityMemory",
    "EntityRelation",
    "EvidenceConnector",
    "ExternalEvidenceRequest",
    "EvidenceGap",
    "EvidencePlan",
    "HttpEvidenceConnector",
    "HttpEvidenceResponse",
    "Evidence",
    "Observation",
    "OpenQuestion",
    "PolicyDecision",
    "PolicyDecisionExecutor",
    "PolicyExecution",
    "ProposalAcceptance",
    "ProposalAcceptancePolicy",
    "ResolutionCase",
    "ResolutionIntent",
    "ResolutionMethod",
    "ResolutionMethodApproval",
    "ResolutionMethodExecution",
    "ResolutionMethodExecutor",
    "SplinkResolutionMethodExecutor",
    "ResolutionDecisionPolicy",
    "ResolutionBudget",
    "ResolutionRun",
    "ReviewedResolutionArtifact",
    "ReviewedResolutionEdge",
    "RelationProposal",
    "ToolCapability",
    "PlannedEvidenceAction",
    "PlannedResolutionMethod",
    "PinnedResolutionMethodExecutor",
    "MethodAssessment",
    "MethodBenchmarkQualification",
    "attach",
    "benchmark_result_bundle_from_record",
    "adapt_coreference_receipt",
    "adapt_reconcile_result",
    "adapt_reviewed_resolution_artifact",
    "reviewed_resolution_evidence",
    "reviewed_reconcile_evidence",
    "new_evidence_action_id",
    "new_entity_id",
    "new_ledger_id",
    "new_resolution_case_id",
    "document_ingestion_from_parsed_document",
    "observation_from_document",
    "observation_from_document_ingestion",
    "qualification_from_evaluated_result",
    "read_benchmark_result_bundle",
    "reviewed_document_evidence",
    "reviewed_document_proposals",
    "write_benchmark_result_bundle",
    "what_would_resolve",
]
